name: iOS Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get

<<<<<<< HEAD
      - name: Build Frameworks
        run: flutter build ios --release --no-codesign

      - name: Force Archive IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     BITCODE_GENERATION_MODE=bitcode \
                     clean archive -archivePath build/Runner.xcarchive

      - name: Prepare Payload
        run: |
          mkdir -p build/Payload
          cp -r build/Runner.xcarchive/Products/Applications/Runner.app build/Payload/
          cd build
          zip -r TelegramAntiBlock.ipa Payload

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-AntiBlock-IPA
          path: build/TelegramAntiBlock.ipa
=======
      # Ключевой хак: собираем только бинарники, не пытаясь подписать приложение
      - name: Build iOS Archive
        run: |
          flutter build ios --release --no-codesign
          
      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -vr TelegramAntiBlock.ipa Payload/

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: AntiBlock-Release
          path: TelegramAntiBlock.ipa
>>>>>>> 17107ec (Real TG logic)
