name: iOS Build
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      - run: flutter pub get

      - name: Build Frameworks
        run: flutter build ios --release --no-codesign

      - name: Force Archive IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -sdk iphoneos \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="" \
                     BITCODE_GENERATION_MODE=bitcode \
                     clean archive -archivePath build/Runner.xcarchive

      - name: Prepare Payload
        run: |
          mkdir -p build/Payload
          cp -r build/Runner.xcarchive/Products/Applications/Runner.app build/Payload/
          cd build
          zip -r TelegramAntiBlock.ipa Payload

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-AntiBlock-IPA
          path: build/TelegramAntiBlock.ipa
